// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateRuleInput struct {
	Type       string       `json:"type"`
	EventType  string       `json:"eventType"`
	Count      *int         `json:"count,omitempty"`
	Conditions string       `json:"conditions"`
	Reward     *RewardInput `json:"reward"`
	Enabled    bool         `json:"enabled"`
}

type Mutation struct {
}

type Query struct {
}

type Reward struct {
	Type        string `json:"type"`
	Amount      *int   `json:"amount,omitempty"`
	Description string `json:"description"`
}

type RewardInput struct {
	Type        string `json:"type"`
	Amount      *int   `json:"amount,omitempty"`
	Description string `json:"description"`
}

type Rule struct {
	ID         string  `json:"id"`
	Type       string  `json:"type"`
	EventType  string  `json:"eventType"`
	Count      *int    `json:"count,omitempty"`
	Conditions string  `json:"conditions"`
	Reward     *Reward `json:"reward"`
	Enabled    bool    `json:"enabled"`
}

type UpdateRuleInput struct {
	Type       *string      `json:"type,omitempty"`
	EventType  *string      `json:"eventType,omitempty"`
	Count      *int         `json:"count,omitempty"`
	Conditions *string      `json:"conditions,omitempty"`
	Reward     *RewardInput `json:"reward,omitempty"`
	Enabled    *bool        `json:"enabled,omitempty"`
}
