// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Course struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	Category *Category `json:"category"`
}

type Query struct {
}
