// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"time"
)

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Course struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Category  *Category `json:"category"`
	CreatedAt time.Time `json:"createdAt"`
}

type Query struct {
}
