package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"
)

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context, id *string) ([]*Course, error) {
	panic(fmt.Errorf("not implemented: Courses - courses"))
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
